name: "Install Cachix"

inputs:
  authToken:
    required: true

runs:
  using: "composite"
  steps:
      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v17

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v10
        with:
          name: dliberalesso
          authToken: "${{ inputs.authToken }}"
          extraPullNames: cachix, nix-community

      # Needed because cachix is also installed by Home Manager
      - name: "Set priority flag for Cachix 🚩"
        run: nix-env --set-flag priority 0 cachix
