name: "Build & Cache"

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

    paths-ignore:
      - "LICENSE"
      - "README.md"
      - ".editorconfig"
      - ".git-crypt/**"
      - ".gitattributes"
      - ".gitignore"

  workflow_dispatch:

jobs:
  build-cache:
    name: "Build & Cache"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: "Making Room for Nix to Thrive 🌱"
        uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: "carve"

      - name: "Installing Nix"
        uses: DeterminateSystems/determinate-nix-action@v3
        with:
          extra-conf: |
            lazy-trees = true
            experimental-features = pipe-operators
            extra-substituters = https://nix-community.cachix.org https://cachix.cachix.org https://catppuccin.cachix.org https://hyprland.cachix.org https://install.determinate.systems
            extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM= catppuccin.cachix.org-1:noG/4HkbhJb+lUAdKrph6LaozJvAeEEZj4N732IysmU= hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc= cache.flakehub.com-3:hJuILl5sVK4iKm86JzgdXW12Y2Hwd5G07qKtHTOcDCM=

      - name: "Installing Cachix"
        uses: cachix/cachix-action@v16
        with:
          name: dliberalesso
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: cachix, nix-community

      - name: "Prefetching inputs"
        run: nix flake prefetch-inputs

      - name: "Building all flake outputs with omnix"
        run: nix run .#omnix-ci
