name: "Build & Cache"

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

    paths-ignore:
      - "LICENSE"
      - "README.md"
      - ".editorconfig"
      - ".git-crypt/**"
      - ".gitattributes"
      - ".gitignore"

  workflow_dispatch:

jobs:
  build-cache:
    name: "Build & Cache"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6

      - name: "Making Room for Nix to Thrive 🌱"
        uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: "carve"

      - name: "Installing Nix"
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            always-allow-substitutes = true
            builders-use-substitutes = true
            experimental-features = flakes nix-command
            extra-substituters = https://dliberalesso.cachix.org https://nix-community.cachix.org https://cachix.cachix.org https://catppuccin.cachix.org https://hyprland.cachix.org https://cache.numtide.com
            extra-trusted-public-keys = dliberalesso.cachix.org-1:7qs1S5Qd766dYFU86nVux/wRMZ8UEUbhn3Qxp/TwiOc= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM= catppuccin.cachix.org-1:noG/4HkbhJb+lUAdKrph6LaozJvAeEEZj4N732IysmU= hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc= niks3.numtide.com-1:DTx8wZduET09hRmMtKdQDxNNthLQETkc/yaX7M4qK0g=
            keep-env-derivations = true
            keep-outputs = true
          github_access_token: ${{ secrets.PAT }}

      - name: "Installing Cachix"
        uses: cachix/cachix-action@v17
        with:
          name: dliberalesso
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: cachix, nix-community

      - name: "Installing Omnix"
        run: nix profile add nixpkgs#omnix

      - name: "Building all flake outputs with omnix"
        run: om ci
