name: "Home"

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

    paths-ignore:
      - "LICENSE"
      - "README.md"
      - ".editorconfig"
      - ".git-crypt/**"
      - ".gitattributes"
      - ".gitignore"

  workflow_dispatch:

jobs:
  build:
    name: Build & Cache Home
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: "Install Nix ❄️"
        uses: DeterminateSystems/nix-installer-action@v16

      - name: "Install Magic Cache ❄️"
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v15
        with:
          name: dliberalesso
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: cachix, nix-community

      # Needed because cachix is also installed by Home Manager
      # - name: "Set priority flag for Cachix 🚩"
      #  run: nix-env --set-flag priority 0 cachix

      - name: "Build Home Manager config 🏠"
        run: nix build .#homeConfigurations.dli.activationPackage -v -L

      - name: "Test shell"
        run: nix develop -c echo OK
