name: "Home"

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

    paths-ignore:
      - "LICENSE"
      - "README.md"
      - ".editorconfig"
      - ".git-crypt/**"
      - ".gitattributes"
      - ".gitignore"    

  workflow_dispatch:

jobs:
  build:
    name: Build & Cache Home
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v22

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v12
        with:
          name: dliberalesso
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: cachix, nix-community

      # Needed because cachix is also installed by Home Manager
      - name: "Set priority flag for Cachix 🚩"
        shell: bash
        run: nix-env --set-flag priority 0 cachix

      - name: "Build Home Manager config 🏠"
        run: nix build .#homeConfigurations.dli.activationPackage -v -L

      - name: "Test shell"
        run: nix develop -c echo OK
