name: "NixOS"

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

    paths-ignore:
      - "LICENSE"
      - "README.md"
      - ".editorconfig"
      - ".git-crypt/**"
      - ".gitattributes"
      - ".gitignore"    

  workflow_dispatch:

jobs:
  build:
    name: Build & Cache NixOS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v19

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v12
        with:
          name: dliberalesso
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: cachix, nix-community

      - name: "Build NixOS-WSL config ❄️"
        run: nix build .#nixosConfigurations.nixosWSL.config.system.build.toplevel -v -L
